package br.com.pocbackend.springboot.service.queryconstants;

public interface Queries {
	
	
	String LIST_ALUNOS =" SELECT * FROM ALUNO";
	String LIST_ALUNOS_BY_ID =" SELECT * FROM ALUNO WHERE ID_ALUNO = ?";
	String INSERT_ALUNO="INSERT INTO ALUNO(CPF, ENDERECO, ESTADO, MUNICIPIO, TELEFONE, EMAIL) VALUES (?, ?, ?, ?, ?, ?)";
	String UPDATE_ALUNO="UPDATE ALUNO set CPF = ?, ENDERECO = ?, ESTADO = ?, MUNICIPIO = ?, TELEFONE = ?, EMAIL = ?) WHERE ID_ALUNO = ?";
	
	
	String LIST_USUARIOS =" SELECT * FROM USUARIO";
	String LIST_USUARIO_BY_EMAIL =" SELECT * FROM USUARIO WHERE EMAIL = ?";
	
	String LIST_MATRICULAS =" SELECT * FROM MATRICULA";
	String LIST_MATRICULA_BY_ID =" SELECT * FROM MATRICULA WHERE ID_MATRICULA = ?";
	
	String LIST_CURSOS =" SELECT * FROM CURSO";
	String LIST_CURSO_BY_ID =" SELECT * FROM CURSO WHERE ID_CURSO = ?";
	
	String LIST_AVALIACOES =" SELECT * FROM AVALIACAO";
	String LIST_AVALIACAO_BY_ID =" SELECT * FROM AVALIACAO WHERE ID_AVALIACAO = ?";
	
	String LIST_NOTAS =" SELECT * FROM NOTA";
	String LIST_NOTA_BY_ID =" SELECT * FROM NOTA WHERE ID_NOTA = ?";


}
