export const Constantes = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    AUTH_LOGIN: 'auth/login',
    AUTH_REGISTER: 'auth/register',
    AUTH_REGISTER_SUCCESS: 'register-success',
    AUTH_REGISTER_SUCCESS_CONFIRM_NUMBER: 'confirm-number-phone',
    CURSOS_URL: 'cursos',
    NOTAS_URL: 'notas',
    AVALIACOES_URL: 'avaliacoes',
    MATRICULAS_URL: 'matriculas',
    ALUNOS_URL: 'alunos',
    LOGIN_URL: 'login',
    USUARIOS_URL: 'usuarios',
    MATERIAS_URL: 'materias',
    PROFILE_URL: 'profile',
    USER_URL: 'usuario',
    CODE_BRAZIL_SMS: '+55',
    VERIFY_SMS: true,
    USER_CACHE: 'user'
};
